name: generate allure report
on:
  push:
    branches:
      - 'main'

jobs:
  Report:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Run tests
        continue-on-error: true
        run: npm run chromeHeadless

      - name: Generate Allure report
        continue-on-error: true
        run: npm run allure:generate

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ALLURE_TOKEN }}
          publish_dir: ./allure-report
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"