name: generate allure report
on:
  push:
    branches:
      - 'main'

jobs:
  Report:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: Run tests
        continue-on-error: true
        run: npm run chromeHeadless

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
            ref: gh-pages
            path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
            allure_results: allure-results
            allure_history: allure-history
            gh_pages: gh-pages
            allure_report: allure-report
                  
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.ALLURE_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history
